### ISSUE TITLE
Simplify table:method in datastore.py and etl.py

### ISSUE THREAD

**Issue by gschivley** [catalyst-cooperative/pudl#412] opened 2019-09-19 18:22 UTC
Both `pudl.workspace.datastore` and `pudl.etl` have functions with a bunch of `if/else` statements depending on the datasource. As more datasources are added to PUDL this is going to get unwieldy. I'd propose a structure of defining small new functions that are accessed via a dictionary. Really, anything that gets rid of a long list of `if/else` statements.

**Comment by zaneselvans** [comment] 2019-09-19 18:26
This is... definitely true.  I was envisioning this happening as part of #374 and #182, which I would like to take care of before we add EIA 861 or the ISO/LMP data.

**Comment by zaneselvans** [comment] 2019-10-15 14:05
Closing this as a duplicate of #374 and #182 -- we will get rid of the excessive if/else statements!

**Closed by zaneselvans** 2019-10-15 14:05 UTC
Labels: datastore
