### ISSUE TITLE
Fix Identified primary key issues

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#1182] opened 2021-09-02 19:54 UTC
Implement the proposed natural primary keys identified in issue #846

This may also require some minor changes to the transform modules.

**Comment by zaneselvans** [comment] 2021-09-10 04:27
This is mostly a duplicate of the Epic #1212 which includes issues around a few other types of DB constraints that the current data don't quite satisfy.

**Closed by zaneselvans** 2021-09-10 04:27 UTC
Labels: harvest
