### ISSUE TITLE
FERC regressions

### ISSUE THREAD

**Issue by alanawlsn** [catalyst-cooperative/pudl#204] opened 2018-09-28 18:46 UTC
Implement regressions within FERC O&M dataset that will allow us to attribute fixed vs. variable cost components at the (FERC) plant level.

**Comment by zaneselvans** [comment] 2018-09-28 19:52
Also, the scikit-learn python library has [a nice page talking about its collection of linear models](http://scikit-learn.org/stable/modules/linear_model.html), with some background on each one.

The end goal of looking at these costs is really to build some kind of model of the cost per MWh on a per plant basis, that depends on... what?  Like, if we wanted to predict the marginal cost of electricity for a given plant, what would we need?  I think the relevant inputs (independent variables, X) end up being something like:

* plant capacity (MW)
* plant heat rate (mmBTU/MWh)
* capacity factor (unitless)
* fuel heat content (mmBTU/unit)
* fuel price ($/mmBTU or $/unit)
* primary fuel type (categorical -- coal or gas)
* plant technology (categorical)
* year of construction (number? or is it categorial?)

And the output we're trying to obtain is just the cost of a marginal unit of electricity production ($/MWh).

Especially given how little information we have about what goes into all of those different FERC cost categories, and whether or not the utilities are reporting those cost categories in a really standard way, I wonder if we might have better luck just using these simpler inputs / output in the regression?

These inputs would allow terms that are a function of plant capacity (i.e $/MW installed), as well as capacity factor, and of course also true fixed costs. The regression wouldn't be confounded by fuel cost volatility, which are probably one of the larger sources of variance, since it would have all the information required to get the fuel cost component right (heat rate, fuel price, fuel heat content). We could even just leave in all the different fuels with their different prices and heat contents separated if we wanted to (since some coal plants use a non-trivial fraction of gas or oil).

Does that seem sensible?

**Comment by zaneselvans** [comment] 2018-09-28 19:52
Thinking about this some more... don't we really just need to figure out a model for the non-fuel costs since we know pretty much exactly how the fuel costs contribute to the overall cost per MWh? Then we just need to fit the remaining non-fuel costs per MWh to a function of the plant capacity, capacity factor, plant & fuel type, and year/decade of construction. We can leave out the fuel price, heat rate, heat content, etc. since we can assemble that function from scratch, and (I think) have little reason to believe that those variables would have much influence on the other plant costs.  Would we want to include an interaction term to find a dependence on (capacity * capacity factor) (aka net generation) in addition to capacity and capacity factor independently? Or are we interested in just the capacity & net generation terms?

**Comment by michaelpburt** [comment] 2018-09-28 20:36
Hi Zane, This may not be what you are looking for, but many ISO's publish guidance on what the VOM (variable operations and maintenance) costs are on a per-technology basis (aka supercritical coal, subcritical coal, CT, CC, hydro, etc.). This guidance is used widely as an input in marginal cost models. See page 22 of this PJM manual > https://www.pjm.com/-/media/documents/manuals/archive/m15/m15v28-cost-development-guidelines-10-18-2016.ashx

In my experience, VOM is usually sufficient to encompass all costs beyond fuel input and carbon & MATS compliance related costs. Those costs include things like fly ash, urea, chlorine, or other inputs into scrubbers and such. I am not sure what the magnitude of those costs are, but I bet there is some pretty good documentation out there. Off the top of my head, I think they are around $1-$3 per MWhr for big nasty coal plants.

**Comment by zaneselvans** [comment] 2018-10-17 09:14
@michaelpburt I definitely don't completely understand the calculations that PJM is describing in that document but the sense I got was that there's an acceptable VOM number that generators can include in their prices based on the technology of the generator, and that that number may be different from the actual variable expenses they've experienced? Is that right? Is that to compensate for typical expenses that just haven't been experienced by a generator yet? Like how you know the cost of maintenance on a new car isn't $0/mi even if it might look that way for the first few years of operations?  Are the expenses small enough (relative to fuel) and/or uniform enough across different plants of a given technology that it's not really worth trying to extract the particular per-plant expenses? Is the effect of expected but as of yet unrealized O&M large enough that these categorical estimates are more useful than real per-plant expenditures?

**Comment by gschivley** [comment] 2019-03-20 19:52
@alanawlsn and @zaneselvans Let me know if there's anything I can do to help with the cost calculations.

**Comment by zaneselvans** [comment] 2019-03-21 23:44
Okay, I've merged together annualized records from FERC and EIA on the basis of their `report_year`, `plant_id_pudl` and primary fuel type, and plotted some of the more interesting values which are available in both datasets (capacity, fuel cost, total heat content of fuel consumed, net generation), as well as some derived values (heat rate, fuel cost per MWh and mmBTU, capacity factor) against each other, separated out for the coal and gas portions of each of the power plants. The results are below.

One thing that I noted: there were only about 1450 records shared between the two datasets, which seems kind of small (this data is for 2009-2017, the years which we have for both of them). Now in retrospect I realize this is probably (yet again) an artifact of the NA values that are common in the EIA data wiping out a bunch of the aggregated values.

Generally it looks better than I expected it would. Thoughts? @alanawlsn @gschivley @cmgosnell 

![eia_vs_ferc_capacity_mw](https://user-images.githubusercontent.com/596279/54791370-346fda00-4bff-11e9-93e8-3d189c422970.png)
![eia_vs_ferc_net_generation_mwh](https://user-images.githubusercontent.com/596279/54791382-4782aa00-4bff-11e9-85e9-b21c2e6f4583.png)
![eia_vs_ferc_total_mmbtu](https://user-images.githubusercontent.com/596279/54791390-50737b80-4bff-11e9-802c-927f5db631a2.png)
![eia_vs_ferc_opex_fuel](https://user-images.githubusercontent.com/596279/54791395-56695c80-4bff-11e9-8415-7d20f51e67dc.png)
![eia_vs_ferc_capacity_factor](https://user-images.githubusercontent.com/596279/54791409-62edb500-4bff-11e9-945f-7b9b80a36895.png)
![eia_vs_ferc_fuel_cost_per_mmbtu](https://user-images.githubusercontent.com/596279/54791411-697c2c80-4bff-11e9-8538-ec6351238a1b.png)
![eia_vs_ferc_fuel_cost_per_mwh](https://user-images.githubusercontent.com/596279/54791415-6e40e080-4bff-11e9-9d64-7455f7c7c50e.png)
![eia_vs_ferc_heat_rate_mmbtu_mwh](https://user-images.githubusercontent.com/596279/54791428-7b5dcf80-4bff-11e9-8dba-491cded30d08.png)

**Comment by gschivley** [comment] 2019-03-22 13:10
I'm not as familiar with FERC data - who is required to report to them? The plots do show a nice agreement.

**Comment by cmgosnell** [comment] 2021-09-02 14:07
closing because this it no longer relevant. we've generally learned that it is difficult to impossible to categorize the specific O&M lines in FERC as fixed and variable O&M. We have been employing NEMS' breakdown of fixed a variable O&M. See example [here](https://github.com/catalyst-cooperative/carbon-tracker-plants/blob/31b0866b57a0881c2bd7d93f1b51b4c6be6d42d2/src/pudl_ct/guts.py#L1234).

**Closed by cmgosnell** 2021-09-02 14:07 UTC
Labels: ferc1, analysis
