### ISSUE TITLE
Clean up and fill out docstrings for use by sphinx

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#316] opened 2019-06-16 22:25 UTC
The draft documentation, written using [ReStructured Text](https://www.sphinx-doc.org/es/stable/rest.html), is successfully building on [Read The Docs](https://catalyst-cooperative-pudl.readthedocs.io/en/latest/), and all the docstrings conform to the [Google Style](https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google) guide, which can be translated automatically by Sphinx into reST.  However, the contents of the doc strings often needs to be fleshed out -- especially the **module** and **sub-package** level docstrings, which are often only a single line and give no overview of the module.

### A punchlist of all API elements to be distributed:

* [ ] `pudl.analysis.mcoe`
* [ ] `pudl.analysis`
* [ ] `pudl.cli`
* [x] `pudl.constants`
* [x] `pudl.convert.epacems_to_parquet`
* [x] `pudl.convert.ferc1_to_sqlite`
* [ ] `pudl.convert`
* [ ] `pudl.datastore.cli`
* [ ] `pudl.datastore.datastore`
* [ ] `pudl.datastore`
* [x] `pudl.etl_pkg` (will be re-named to `pudl.etl`)
* [ ] `pudl.extract.eia860`
* [ ] `pudl.extract.eia923`
* [ ] `pudl.extract.epacems`
* [ ] `pudl.extract.epaipm`
* [x] `pudl.extract.ferc1`
* [ ] `pudl.extract`
* [x] `pudl.glue.ferc1_eia`
* [x] `pudl.glue`
* [x] `pudl.helpers`
* [ ] `pudl.init` (to be removed)
* [x] `pudl.load`
* [ ] `pudl.output.eia860`
* [ ] `pudl.output.eia923`
* [ ] `pudl.output.export`
* [ ] `pudl.output.ferc1`
* [ ] `pudl.output.glue`
* [ ] `pudl.output.pudltabl`
* [x] `pudl.output`
* [ ] `pudl`
* [ ] `pudl.settings`
* [ ] `pudl.transform.eia860`
* [ ] `pudl.transform.eia923`
* [x] `pudl.transform.eia`
* [ ] `pudl.transform.epacems`
* [ ] `pudl.transform.epaipm`
* [ ] `pudl.transform.ferc1`
* [x] `pudl.transform`

**Comment by cmgosnell** [comment] 2020-01-20 21:21
duplicate of Issue #498

**Closed by cmgosnell** 2020-01-20 21:21 UTC
Labels: docs, ready
